# Generated by Django 5.1.3 on 2024-12-16 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_dt', models.DateTimeField(auto_now=True)),
                ('feedback_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('feedback_phone', models.CharField(max_length=100, verbose_name='Номер телефона')),
            ],
        ),
    ]
